In [1]:
# seed the pseudorandom number generator
from random import seed
from random import random

# seed random number generator
seed(1)

# generate some random numbers
print(random(), random(), random())

# reset the seed
seed(1)

# generate some random numbers
print(random(), random(), random())

0.13436424411240122 0.8474337369372327 0.763774618976614
0.13436424411240122 0.8474337369372327 0.763774618976614


In [5]:
#seedrandomnumbergenerator
seed(1)

#generaterandomnumbersbetween0-1
for _ in range(10):
    value = random()
    print(value)

0.13436424411240122
0.8474337369372327
0.763774618976614
0.2550690257394217
0.49543508709194095
0.4494910647887381
0.651592972722763
0.7887233511355132
0.0938595867742349
0.02834747652200631


In [7]:
from random import randint

#seedrandomnumbergenerator
seed(1)

#generatesomeintegers
for _ in range(10):
    value = randint(0,10)
    print(value)

2
9
1
4
1
7
7
7
10
6


In [9]:
from random import gauss

#seedrandomnumbergenerator
seed(1)

# generate some Gaussian values
for _ in range(10):
    value = gauss(0, 1)
    print(value)

1.2881847531554629
1.449445608699771
0.06633580893826191
-0.7645436509716318
-1.0921732151041414
0.03133451683171687
-1.022103170010873
-1.4368294451025299
0.19931197648375384
0.13337460465860485


In [13]:
from random import choice


seed(1)

# prepare a sequence
sequence = [i for i in range(20)]

print(sequence)
# make choices from the sequence

for _ in range(5):
    selection = choice(sequence)
    print(selection)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
4
18
2
8
3


In [15]:
from random import sample

# seed random number generator
seed(1)

# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)

# select a subset without replacement
subset = sample(sequence, 5)
print(subset)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[4, 18, 2, 8, 3]


In [21]:
from random import shuffle

# seed random number generator
seed(1)

# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)

# randomly shuffle the sequence
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[11, 5, 17, 19, 9, 0, 16, 1, 15, 6, 10, 13, 14, 12, 7, 3, 8, 2, 18, 4]


# Random numbers Numpy

In [24]:
# seed the pseudorandom number generator
from numpy.random import seed
from numpy.random import rand

# seed random number generator
seed(1)

# generate some random numbers
print(rand(3))

# reset the seed
seed(1)

# generate some random numbers
print(rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [26]:
from numpy.random import rand

# seed random number generator
seed(1)

# generate random numbers between 0-1
values = rand(10)
print(values)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [28]:
from numpy.random import randint

# seed random number generator
seed(1)

# generate some integers
values = randint(0, 10, 20)
print(values)

[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9]


In [30]:
from numpy.random import randn

# seed random number generator
seed(1)

# generate some Gaussian values
values = randn(10)
print(values)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]


In [32]:
from numpy.random import shuffle

# seed random number generator
seed(1)

# prepare a sequence
sequence = [i for i in range(20)]
print(sequence)

# randomly shuffle the sequence
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[3, 16, 6, 10, 2, 14, 4, 17, 7, 1, 13, 0, 19, 18, 9, 15, 8, 12, 11, 5]
